### ISSUE TITLE
U-Boot integration

### ISSUE THREAD

**Issue by mjftw** [Witekio/pluma-automation#142]
**Is your feature request related to a problem? Please describe.**
Many target systems will be running U-Boot as their bootloader, and it would be good to have some built in support for this.
This is all currently possible through the Console classes, but it would be nice to have built-in a way to interact with U-Boot from the YAML config files.
Functionality that would be most helpful is the ability to run U-Boot commands, and set environment variables.
This would be enough to configure how a board boots at the start of a test.

**Describe the solution you'd like**
One possible solution would be to use a device action for this.

The tests config file might look like:
```yaml
sequence:
- uboot
  powercycle: true
  env:
    - ipaddr: 192.168.0.10
    - serverip: 192.168.0.11
    - bootargs: /boot/kernel-3-2-1-gentoo root=/dev/sda1 vga=791
    - bootcmd: ...
  command:
    - dhcp
    - mw.w 0x80000100 ...
```

The example above would cause the following actions to happen to the board:
1. The board is turned off
2. The board is turned on
3. The console is watched for the U-Boot boot text E.g. "U-Boot 2013.04 (May 14 2019 - 12:16:13) ...... Hit any key to stop autoboot: 3"
4. A key would be pressed to break into U-Boot shell
5. A setenv command would be run for each of the environment variables specified in `env:`
6. All of the commands in `command` would be run on the board, in the order specified.

This could even be extended to have each of the commands have optional expected output and error output parameters, which can be used to trigger an immediate failure.

E.g.
```yaml
sequence:
- uboot
  powercycle: true
  command:
    - printenv baudrate:
      must_match: 115200
      must_not_match: 9600
```
