### ISSUE TITLE
Pluma sometimes fails to wire yaml args to __init__ args for TestBase classes

### ISSUE THREAD

**Issue by mjftw** [Witekio/pluma-automation#73]
**Describe the bug**
```
 (venv) merlin@pangolin:~/projects/pluma-automation$   cd /home/merlin/projects/pluma-automation ; /usr/bin/env /home/merlin/projects/pluma-automation/venv/bin/python3.6 /home/merlin/.vscod/extensions/ms-python.python-2020.8.109390/pythonFiles/lib/python/debugpy/launcher 43679 -- -m pluma -c /home/merlin/projects/pluma-automation/pluma.yml -t /home/merlin/projects/pluma-automation/pluma-target.yml 
No console defined in the device configuration file
The following configuration attributes were not recognized or not used:
{'testsuite.filesystem.FileIsRegular': {'path': '/bin/bash', 'run_on_host': True}}
```

pluma.yml
```
settings:
  continue_on_fail: true
  iterations: 1

sequence:
- core_tests:
    include: [testsuite.filesystem]
    exclude: []
    parameters:
      testsuite.filesystem.FileIsRegular:
        path: '/bin/bash'
        run_on_host: true
```

pluma-target.yml
```
system:
  prompt_regex: "\\S+@\\S+:"
  credentials:
    login: mendel
    password: mendel
```

Tests being run: (new files) `pluma.plugins.testsuite.filesystem.py`
```python
class FileExists(ShellTest):
    def __init__(self, board: Board, path: str, run_on_host: bool = False):
        super().__init__(board, script=f'[ -e "{path}" ]', runs_in_shell=True,
                         run_on_host=run_on_host)


class FileIsRegular(ShellTest):
    def __init__(self, board: Board, path: str, run_on_host: bool = False):
        super().__init__(board, script=f'[ -f "{path}" ]', runs_in_shell=True,
                         run_on_host=run_on_host)
```

Issue goes away when specifying `FileExists` instead, despite having the same arguments.
```
settings:
  continue_on_fail: true
  iterations: 1

sequence:
- core_tests:
    include: [testsuite.filesystem]
    exclude: []
    parameters:
      testsuite.filesystem.FileExists:
        path: '/bin/bash'
        run_on_host: true
```

```
(venv) merlin@pangolin:~/projects/pluma-automation$  cd /home/merlin/projects/pluma-automation ; /usr/bin/env /home/merlin/projects/pluma-automation/venv/bin/python3.6 /home/merlin/.vscode/extensions/ms-python.python-2020.8.109390/pythonFiles/lib/python/debugpy/launcher 41587 -- -m pluma -c /home/merlin/projects/pluma-automation/pluma.yml -t /home/merlin/projects/pluma-automation/pluma-target.yml 
No console defined in the device configuration file
[ 0%] pluma.plugins.testsuite.filesystem.FileExists[1] - test_body          PASS
Test iteration complete: PASS
All tests were successful.
(venv) merlin@pangolin:~/projects/pluma-automation$
```

**Expected behaviour**
Parameters in pluma.yml are detected and wired to the __init__ args for the test.

**System info**
- Ubuntu 18.04
- 3.6
