### ISSUE TITLE
"pluma tests" should show all available tests

### ISSUE THREAD

**Issue by mjftw** [Witekio/pluma-automation#93]
**Is your feature request related to a problem? Please describe.**
When running `pluma tests` it would be useful to see all available tests, rather than just the ones that the TestsProviders have found in their include paths.

### With the tests in the include path
```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma --plugin ./myplugindir tests

Device actions:
    [x] {'copytodevice'}
          {"file": "/home/merlin/projects/pluma-automation/README.md", "destination": "/tmp/", "timeout": 10}

Core tests (testsuite, Python):
    [x] mytests.SayHello
    [ ] testsuite.kernel.KernelModulesLoaded
    [ ] testsuite.memory.MemorySize
    [ ] testsuite.networking.IperfBandwidth
    [ ] testsuite.networking.NetworkingTestBase
    [ ] testsuite.networking.RespondsToPing

Configuration and tests successfully validated.
```

pluma.yml
```yaml
settings:
  continue_on_fail: true
  iterations: 1

sequence:
- copytodevice:
    file: '/home/merlin/projects/pluma-automation/README.md'
    destination: '/tmp/'
    timeout: 10
- core_tests:
    include: ['mytests']
```

### Without the tests in the include path

```
(venv) merlin@pangolin:~/projects/pluma-automation$ pluma --plugin ./myplugindir tests

Device actions:
    [x] {'copytodevice'}
          {"file": "/home/merlin/projects/pluma-automation/README.md", "destination": "/tmp/", "timeout": 10}

Configuration and tests successfully validated.
```

pluma.yml
```yaml
settings:
  continue_on_fail: true
  iterations: 1

sequence:
- copytodevice:
    file: '/home/merlin/projects/pluma-automation/README.md'
    destination: '/tmp/'
    timeout: 10
# - core_tests:
#     include: ['mytests']

```

**Describe the solution you'd like**
I would like that all accessible tests be shown in the list, but marked as unselected.
This would allow users to:
* Know what tests there are available to enable
* Know that their plugin tests have been detected as they write them, without having to write yaml to run them

In the above second example I'd like to see:

```
Device actions:
    [x] {'copytodevice'}
          {"file": "/home/merlin/projects/pluma-automation/README.md", "destination": "/tmp/", "timeout": 10}

Core tests (testsuite, Python):
    [ ] mytests.SayHello
    [ ] testsuite.kernel.KernelModulesLoaded
    [ ] testsuite.memory.MemorySize
    [ ] testsuite.networking.IperfBandwidth
    [ ] testsuite.networking.NetworkingTestBase
    [ ] testsuite.networking.RespondsToPing
``` 

It would be good to also expose this "available tests" lists functionality in some easily useable API calls as I expect we'll need this at a later date if we add any other kind of user interface.

I'd like to also see all the available device actions too, as users could add these in their plugins as well.

**Describe alternatives you've considered**
Alternatively we could add a CLI option like `pluma check --all/-a` to optionally display everything, but might be easier for a new user to just see it all up front. A different (new) pluma sub-command could even be used.
